version: "3.7"
services:

  # El contenedor del mysql 
  sport-center-mysql:
    container_name: sport-center-mysql
    image: mysql/mysql-server:8.0.32
    restart: always
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=center
      - MYSQL_USER=sport-center
      - MYSQL_PASSWORD=center
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command:
      - '--disable-log-bin=ON --bind-address=0.0.0.0 --event_scheduler=ON --log_bin_trust_function_creators=ON --max_connections=300 --innodb_print_all_deadlocks=1 --default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306
    networks:
      - sport-center-network

  # El contenedor del servidor php 
  sport-center-backend:
    build:
      args:
        user: sport-center
        uid: 1000
      context: ../backend
      dockerfile: Dockerfile
    image: sport-center-backend
    container_name: sport-center-backend
    working_dir: /var/www/
    volumes:
      - ../backend/:/var/www
    networks:
      - sport-center-network

  # El contenedor que expone el servicio php
  sport-center-nginx-backend:
    image: nginx:1.17-alpine
    container_name: sport-center-nginx-
    ports:
      - 8000:80
    volumes:
      - ../backend:/var/www
      - ../backend/nginx/:/etc/nginx/conf.d
    networks:
      - sport-center-network

  # El contenedor que expone el frontend
  sport-center-frontend:
    container_name: sport-center-front
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - sport-center-network          

networks:
  sport-center-network:
    driver: bridge